# Generated by Django 3.0.2 on 2020-02-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200204_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='usibility',
            new_name='usability',
        ),
        migrations.AddField(
            model_name='post',
            name='tweet1',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tweet2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tweet3',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tweet4',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tweet5',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
