# Generated by Django 3.0.2 on 2020-02-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200210_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tweet1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweet2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweet3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweet4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweet5',
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=250)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
