# Generated by Django 3.0.2 on 2020-03-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=250)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.Filter')),
            ],
        ),
    ]
